insert into customer(name, age, active) values ("alice", 50, true);
insert into customer(name, age, active) values ("bob", 20, false);
insert into customer(name, age, active) values ("charlie", 30, true);
insert into product_table ( name, category, price, manufacturer, unitInStock, description) values ("Nike", "Shoes", 123 , "신발1", 20 ,"신발 설명1");	
insert into product_table ( name, category, price, manufacturer, unitInStock, description) values ("adidas", "Shoes", 1234 , "신발2", 20 ,"신발 설명 2");
insert into product_table ( name, category, price, manufacturer, unitInStock, description) values ("Vans", "Shoes", 12345 , "신발3", 20 ,"신발 설명3");	
insert into product_table ( name, category, price, manufacturer, unitInStock, description) values ("kumkang", "Shoes", 123456 , "신발4", 20 ,"신발 설명4");	
insert into product_table ( name, category, price, manufacturer, unitInStock, description) values ("Hansung", "PC", 234 , "PC1", 20 ,"PC 설명1")	;
insert into product_table ( name, category, price, manufacturer, unitInStock, description) values ("Samsung", "PC", 2345 , "PC2", 20 ,"PC 설명2")	;
insert into product_table ( name, category, price, manufacturer, unitInStock, description) values ("LG", "PC", 234546 , "PC3", 20 ,"PC 설명3")	;
insert into product_table ( name, category, price, manufacturer, unitInStock, description) values ("IBM", "PC", 234567 , "PC4", 20 ,"PC 설명4")	;
insert into product_table ( name, category, price, manufacturer, unitInStock, description) values ("나에게는 나를 파괴할 권리가 있다", "Book", 456 , "김영하 1", 20 ,"어느 작가의 말을 제목으로 인용한 책")	;
insert into product_table ( name, category, price, manufacturer, unitInStock, description) values ("살인자의 기억법", "Book", 45678 , "김영하 2", 20 ,"치매걸린 노년 살인자의 이야기");	