insert into customer(name, age, active) values ("alice", 50, true);
insert into customer(name, age, active) values ("bob", 20, false);
insert into customer(name, age, active) values ("charlie", 30, true);
insert into product ( name, category, price, manufacturer, unitinstock, description) values ("세탁기1", "washer", 1000 , "삼성",20 ,"라스트 세탁기");	
insert into product ( name, category, price, manufacturer, unitinstock, description) values ("세탁기2", "washer", 1000 , "삼성",20 ,"라스트 세탁기");
insert into product ( name, category, price, manufacturer, unitinstock, description) values ("세탁기3", "washer", 1000 , "삼성",20 ,"라스트 세탁기");	
insert into product ( name, category, price, manufacturer, unitinstock, description) values ("세탁기4", "washer2", 1000 , "삼성",20 ,"라스트 세탁기");	
insert into product ( name, category, price, manufacturer, unitinstock, description) values ("세탁기5", "washer2", 1000 , "삼성",20 ,"라스트 세탁기")	;
insert into product ( name, category, price, manufacturer, unitinstock, description) values ("세탁기6", "washer2", 1000 , "삼성",20 ,"라스트 세탁기")	;
insert into product ( name, category, price, manufacturer, unitinstock, description) values ("세탁기7", "washer3", 1000 , "삼성",20 ,"라스트 세탁기")	;
insert into product ( name, category, price, manufacturer, unitinstock, description) values ("세탁기8", "washer3", 1000 , "삼성",20 ,"라스트 세탁기")	;
insert into product ( name, category, price, manufacturer, unitinstock, description) values ("세탁기9", "washer3", 1000 , "삼성",20 ,"라스트 세탁기")	;
insert into product ( name, category, price, manufacturer, unitinstock, description) values ("세탁기10", "washer4", 1000 , "삼성",20 ,"라스트 세탁기");	